DROP TABLE IF EXISTS "users";

CREATE TABLE "users"(
    idUsers INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    prenom VARCHAR(20) NOT NULL,
    nom VARCHAR(25) NOT NULL,
    sexe VARCHAR(9),
    pseudo VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY(idUsers)
    )ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES "users" WRITE;